"""alerte prise en main humaine

Revision ID: 00d3a605d55a
Revises: 23750fe0114c
Create Date: 2026-09-25 21:15:24.359750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00d3a605d55a'
down_revision = '23750fe0114c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('human_alert_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'human_alert_sent_at')
    # ### end Alembic commands ###
