"""sprint 8 - integration shopify

Revision ID: 012e399c3def
Revises: e5668e167fb1
Create Date: 2026-09-21 07:21:37.322804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '012e399c3def'
down_revision = 'e5668e167fb1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecommerce_connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.Enum('SHOPIFY', name='ecommerce_platform'), nullable=False),
    sa.Column('shop_domain', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.String(length=2048), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('auto_sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('sync_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_status', sa.Enum('NEVER_SYNCED', 'SUCCESS', 'FAILED', name='sync_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'platform', name='uq_ecommerce_tenant_platform')
    )
    op.create_index(op.f('ix_ecommerce_connections_tenant_id'), 'ecommerce_connections', ['tenant_id'], unique=False)
    op.add_column('products', sa.Column('external_source', sa.String(length=32), nullable=True))
    op.add_column('products', sa.Column('external_id', sa.String(length=128), nullable=True))
    op.create_unique_constraint('uq_products_tenant_external', 'products', ['tenant_id', 'external_source', 'external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_products_tenant_external', 'products', type_='unique')
    op.drop_column('products', 'external_id')
    op.drop_column('products', 'external_source')
    op.drop_index(op.f('ix_ecommerce_connections_tenant_id'), table_name='ecommerce_connections')
    op.drop_table('ecommerce_connections')
    # ### end Alembic commands ###
