"""lot 15 strategies objections

Revision ID: 066aaad3e12e
Revises: fb4bae1d1734
Create Date: 2026-09-26 16:56:23.015116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '066aaad3e12e'
down_revision = 'fb4bae1d1734'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_strategy_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('disabled_strategies', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.add_column('message_signals', sa.Column('strategy', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message_signals', 'strategy')
    op.drop_table('tenant_strategy_settings')
    # ### end Alembic commands ###
