"""sprint 23 - consentement marketing trace

Revision ID: 11f17610b145
Revises: e0d26d938411
Create Date: 2026-09-22 18:15:16.923990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11f17610b145'
down_revision = 'e0d26d938411'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('marketing_consent_given_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('customers', sa.Column('marketing_consent_source', sa.String(length=32), nullable=True))
    op.add_column('customers', sa.Column('marketing_consent_withdrawn_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'marketing_consent_withdrawn_at')
    op.drop_column('customers', 'marketing_consent_source')
    op.drop_column('customers', 'marketing_consent_given_at')
    # ### end Alembic commands ###
