"""sprint 11 - website url et ecrans dashboard

Revision ID: 19a5bedf9abf
Revises: ee1bce100fac
Create Date: 2026-09-21 13:45:57.784957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a5bedf9abf'
down_revision = 'ee1bce100fac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('website_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'website_url')
    # ### end Alembic commands ###
