"""lot 3 - 2fa email otp

Revision ID: 1c4449534782
Revises: e5cd1d50cf18
Create Date: 2026-09-23 16:32:24.764270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c4449534782'
down_revision = 'e5cd1d50cf18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mfa_otp_code_hash', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('mfa_otp_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mfa_otp_expires_at')
    op.drop_column('users', 'mfa_otp_code_hash')
    # ### end Alembic commands ###
