"""sprint 19 - demo instantanee

Revision ID: 1f8f55c925be
Revises: 33d6756bb706
Create Date: 2026-09-21 19:42:21.765999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f8f55c925be'
down_revision = '33d6756bb706'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('is_demo', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'is_demo')
    # ### end Alembic commands ###
