"""liens whatsapp et widgets

Revision ID: 23750fe0114c
Revises: 7a2e84f35f6a
Create Date: 2026-09-25 19:20:29.214799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23750fe0114c'
down_revision = '7a2e84f35f6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_points',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('greeting', sa.String(length=300), nullable=False),
    sa.Column('position', sa.String(length=8), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_contact_point_code')
    )
    op.create_index(op.f('ix_contact_points_code'), 'contact_points', ['code'], unique=False)
    op.create_index(op.f('ix_contact_points_tenant_id'), 'contact_points', ['tenant_id'], unique=False)
    op.add_column('customers', sa.Column('acquisition_contact_point_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_customers_acquisition_contact_point_id'), 'customers', ['acquisition_contact_point_id'], unique=False)
    op.create_foreign_key('fk_customers_acquisition_contact_point_id', 'customers', 'contact_points', ['acquisition_contact_point_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_customers_acquisition_contact_point_id', 'customers', type_='foreignkey')
    op.drop_index(op.f('ix_customers_acquisition_contact_point_id'), table_name='customers')
    op.drop_column('customers', 'acquisition_contact_point_id')
    op.drop_index(op.f('ix_contact_points_tenant_id'), table_name='contact_points')
    op.drop_index(op.f('ix_contact_points_code'), table_name='contact_points')
    op.drop_table('contact_points')
    # ### end Alembic commands ###
