"""sprint 14 - relances automatiques

Revision ID: 26caeef17d23
Revises: 6c0e46a6c080
Create Date: 2026-09-21 14:22:45.497664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26caeef17d23'
down_revision = '6c0e46a6c080'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_followup_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('first_followup_hours', sa.Integer(), nullable=False),
    sa.Column('first_message', sa.Text(), nullable=False),
    sa.Column('second_followup_hours', sa.Integer(), nullable=False),
    sa.Column('second_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', name='uq_followup_settings_tenant')
    )
    op.create_index(op.f('ix_tenant_followup_settings_tenant_id'), 'tenant_followup_settings', ['tenant_id'], unique=False)
    op.add_column('conversations', sa.Column('followup_stage', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('conversations', sa.Column('last_followup_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'last_followup_at')
    op.drop_column('conversations', 'followup_stage')
    op.drop_index(op.f('ix_tenant_followup_settings_tenant_id'), table_name='tenant_followup_settings')
    op.drop_table('tenant_followup_settings')
    # ### end Alembic commands ###
