"""lot 4 - commission sur ventes

Revision ID: 41df4ede943c
Revises: 1c4449534782
Create Date: 2026-09-24 07:53:51.426438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41df4ede943c'
down_revision = '1c4449534782'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_commissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('order_total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('commission_rate_applied', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index(op.f('ix_order_commissions_tenant_id'), 'order_commissions', ['tenant_id'], unique=False)
    op.add_column('tenants', sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('tenants', sa.Column('payment_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'payment_link')
    op.drop_column('tenants', 'commission_rate')
    op.drop_index(op.f('ix_order_commissions_tenant_id'), table_name='order_commissions')
    op.drop_table('order_commissions')
    # ### end Alembic commands ###
