"""sprint 13 - upselling produits complementaires

Revision ID: 6c0e46a6c080
Revises: fc8a83194cef
Create Date: 2026-09-21 14:12:00.032705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c0e46a6c080'
down_revision = 'fc8a83194cef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_complements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('complement_product_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['complement_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'complement_product_id', name='uq_product_complement_pair')
    )
    op.create_index(op.f('ix_product_complements_product_id'), 'product_complements', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_complements_tenant_id'), 'product_complements', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_complements_tenant_id'), table_name='product_complements')
    op.drop_index(op.f('ix_product_complements_product_id'), table_name='product_complements')
    op.drop_table('product_complements')
    # ### end Alembic commands ###
