"""source du retrait de consentement

Revision ID: 7a2e84f35f6a
Revises: 9cb88ad8a587
Create Date: 2026-09-25 16:55:31.452914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a2e84f35f6a'
down_revision = '9cb88ad8a587'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('marketing_consent_withdrawn_source', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'marketing_consent_withdrawn_source')
    # ### end Alembic commands ###
