"""phase 0 opportunites de vente

Revision ID: 7eff3b216efc
Revises: 00d3a605d55a
Create Date: 2026-09-26 12:13:05.967169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eff3b216efc'
down_revision = '00d3a605d55a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_opportunities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_customer_message_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outcome', sa.String(length=24), nullable=False),
    sa.Column('is_first_opportunity', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('contact_point_id', sa.Uuid(), nullable=True),
    sa.Column('is_returning_buyer', sa.Boolean(), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('followup_sent', sa.Boolean(), nullable=False),
    sa.Column('customer_message_count', sa.Integer(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('order_count', sa.Integer(), nullable=False),
    sa.Column('order_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('transfer_reason', sa.String(length=300), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_opportunities_conversation_id'), 'sales_opportunities', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_sales_opportunities_customer_id'), 'sales_opportunities', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sales_opportunities_outcome'), 'sales_opportunities', ['outcome'], unique=False)
    op.create_index(op.f('ix_sales_opportunities_started_at'), 'sales_opportunities', ['started_at'], unique=False)
    op.create_index(op.f('ix_sales_opportunities_tenant_id'), 'sales_opportunities', ['tenant_id'], unique=False)
    op.add_column('orders', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'paid_at')
    op.drop_index(op.f('ix_sales_opportunities_tenant_id'), table_name='sales_opportunities')
    op.drop_index(op.f('ix_sales_opportunities_started_at'), table_name='sales_opportunities')
    op.drop_index(op.f('ix_sales_opportunities_outcome'), table_name='sales_opportunities')
    op.drop_index(op.f('ix_sales_opportunities_customer_id'), table_name='sales_opportunities')
    op.drop_index(op.f('ix_sales_opportunities_conversation_id'), table_name='sales_opportunities')
    op.drop_table('sales_opportunities')
    # ### end Alembic commands ###
