"""sprint 16 - memoire client

Revision ID: 827b217070c0
Revises: 96639c44b045
Create Date: 2026-09-21 18:59:58.169117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '827b217070c0'
down_revision = '96639c44b045'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_product_views',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('first_viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'customer_id', 'product_id', name='uq_customer_product_view')
    )
    op.create_index(op.f('ix_customer_product_views_customer_id'), 'customer_product_views', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_product_views_tenant_id'), 'customer_product_views', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_product_views_tenant_id'), table_name='customer_product_views')
    op.drop_index(op.f('ix_customer_product_views_customer_id'), table_name='customer_product_views')
    op.drop_table('customer_product_views')
    # ### end Alembic commands ###
