"""sprint 15 - negociation de prix

Revision ID: 96639c44b045
Revises: 26caeef17d23
Create Date: 2026-09-21 18:47:08.278987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96639c44b045'
down_revision = '26caeef17d23'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_negotiation_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('max_discount_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_rounds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', name='uq_negotiation_settings_tenant')
    )
    op.create_index(op.f('ix_tenant_negotiation_settings_tenant_id'), 'tenant_negotiation_settings', ['tenant_id'], unique=False)
    op.create_table('negotiations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('initial_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('last_proposed_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('final_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('rounds', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'ACCEPTED', 'ESCALATED', name='negotiation_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_negotiations_conversation_id'), 'negotiations', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_negotiations_tenant_id'), 'negotiations', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_negotiations_tenant_id'), table_name='negotiations')
    op.drop_index(op.f('ix_negotiations_conversation_id'), table_name='negotiations')
    op.drop_table('negotiations')
    op.drop_index(op.f('ix_tenant_negotiation_settings_tenant_id'), table_name='tenant_negotiation_settings')
    op.drop_table('tenant_negotiation_settings')
    # ### end Alembic commands ###
