"""sprint 17 - recommandations intelligentes

Revision ID: a147e7dd3291
Revises: 827b217070c0
Create Date: 2026-09-21 19:07:15.525214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a147e7dd3291'
down_revision = '827b217070c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('cost_price', sa.Numeric(precision=14, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'cost_price')
    # ### end Alembic commands ###
