"""lot 38 tutoiement vouvoiement

Revision ID: a38c5e2f9b71
Revises: f37b4c8d1a20
Create Date: 2026-10-02 11:22:11.012963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a38c5e2f9b71'
down_revision = 'f37b4c8d1a20'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('address_form', sa.String(length=8), server_default='VOUS', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'address_form')
    # ### end Alembic commands ###
