"""sprint 20 - freemium qr codes promotion demo

Revision ID: adbe2948ecee
Revises: 1f8f55c925be
Create Date: 2026-09-22 12:20:45.439786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adbe2948ecee'
down_revision = '1f8f55c925be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_qr_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('scan_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_product_qr_code')
    )
    op.create_index(op.f('ix_product_qr_codes_code'), 'product_qr_codes', ['code'], unique=False)
    op.create_index(op.f('ix_product_qr_codes_tenant_id'), 'product_qr_codes', ['tenant_id'], unique=False)
    op.add_column('tenants', sa.Column('is_paid', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('whatsapp_accounts', sa.Column('display_phone_number', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whatsapp_accounts', 'display_phone_number')
    op.drop_column('tenants', 'is_paid')
    op.drop_index(op.f('ix_product_qr_codes_tenant_id'), table_name='product_qr_codes')
    op.drop_index(op.f('ix_product_qr_codes_code'), table_name='product_qr_codes')
    op.drop_table('product_qr_codes')
    # ### end Alembic commands ###
