"""lot 40 emails commande

Revision ID: b40e7d1c3a58
Revises: a38c5e2f9b71
Create Date: 2026-10-02 12:13:27.359664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b40e7d1c3a58'
down_revision = 'a38c5e2f9b71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('recap_emailed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('receipt_emailed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'receipt_emailed_at')
    op.drop_column('orders', 'recap_emailed_at')
    # ### end Alembic commands ###
