"""sprint 2 - whatsapp

Revision ID: bb9620660599
Revises: 13aaac4f12b7
Create Date: 2026-09-21 00:15:38.179579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb9620660599'
down_revision = '13aaac4f12b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_send_audit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('permission_checked', sa.String(length=64), nullable=False),
    sa.Column('result', sa.Enum('SENT', 'DENIED_403', 'DENIED_QUOTA', name='send_result'), nullable=False),
    sa.Column('send_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_send_audit_send_date'), 'message_send_audit', ['send_date'], unique=False)
    op.create_index(op.f('ix_message_send_audit_tenant_id'), 'message_send_audit', ['tenant_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('whatsapp_number', sa.String(length=32), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'whatsapp_number', name='uq_customers_tenant_whatsapp')
    )
    op.create_index(op.f('ix_customers_tenant_id'), 'customers', ['tenant_id'], unique=False)
    op.create_table('tenant_messaging_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('outbound_mode', sa.Enum('AI_ONLY', 'AI_PLUS_HUMAN', 'COMMERCIAL_ENABLED', name='outbound_mode'), nullable=False),
    sa.Column('kill_switch', sa.Enum('ALLOWED', 'BLOCKED', name='kill_switch'), nullable=False),
    sa.Column('daily_outbound_limit', sa.Integer(), nullable=False),
    sa.Column('templates_only', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_messaging_settings_tenant_id'), 'tenant_messaging_settings', ['tenant_id'], unique=True)
    op.create_table('whatsapp_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('waba_id', sa.String(length=64), nullable=False),
    sa.Column('phone_number_id', sa.String(length=64), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('display_name_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='display_name_status'), nullable=False),
    sa.Column('system_user_token', sa.String(length=2048), nullable=False),
    sa.Column('coexistence_mode', sa.Boolean(), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=True),
    sa.Column('business_verification_status', sa.Enum('NOT_SUBMITTED', 'PENDING', 'APPROVED', 'FAILED', name='business_verification_status'), nullable=False),
    sa.Column('business_verification_submitted_by', sa.Enum('SELF', 'PLATFORM', name='verification_submitted_by'), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_accounts_phone_number_id'), 'whatsapp_accounts', ['phone_number_id'], unique=True)
    op.create_index(op.f('ix_whatsapp_accounts_tenant_id'), 'whatsapp_accounts', ['tenant_id'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'WAITING_CUSTOMER', 'WAITING_HUMAN', 'CLOSED', name='conversation_status'), nullable=False),
    sa.Column('assigned_agent', sa.Uuid(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_agent'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_customer_id'), 'conversations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_conversations_tenant_id'), 'conversations', ['tenant_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('sender', sa.Enum('CUSTOMER', 'AI', 'HUMAN', 'SYSTEM', name='message_sender'), nullable=False),
    sa.Column('message_type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_tenant_id'), 'messages', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_tenant_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversations_tenant_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_customer_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_whatsapp_accounts_tenant_id'), table_name='whatsapp_accounts')
    op.drop_index(op.f('ix_whatsapp_accounts_phone_number_id'), table_name='whatsapp_accounts')
    op.drop_table('whatsapp_accounts')
    op.drop_index(op.f('ix_tenant_messaging_settings_tenant_id'), table_name='tenant_messaging_settings')
    op.drop_table('tenant_messaging_settings')
    op.drop_index(op.f('ix_customers_tenant_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_message_send_audit_tenant_id'), table_name='message_send_audit')
    op.drop_index(op.f('ix_message_send_audit_send_date'), table_name='message_send_audit')
    op.drop_table('message_send_audit')
    # ### end Alembic commands ###
