"""sprint 21 - plan unifie free independant starter pro entreprise

Revision ID: d1ee0898e653
Revises: adbe2948ecee
Create Date: 2026-09-22 17:34:05.240764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd1ee0898e653'
down_revision = 'adbe2948ecee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # 0. add_column ne crée pas le type énuméré tout seul (contrairement à create_table) :
    # il faut le créer explicitement en premier, sinon l'ALTER TABLE échoue.
    tenant_plan_enum = sa.Enum('FREE', 'INDEPENDANT', 'STARTER', 'PRO', 'ENTERPRISE', name='tenant_plan')
    tenant_plan_enum.create(op.get_bind(), checkfirst=True)

    # 1. Nouvelle colonne avec défaut, pour ne jamais échouer sur les lignes déjà existantes.
    op.add_column(
        'tenants',
        sa.Column('plan', tenant_plan_enum, nullable=False, server_default='FREE'),
    )

    # 2. Migration des données AVANT de supprimer is_paid : tout tenant marqué payant
    # passe au palier Indépendant (le plus proche de l'ancien "payant" générique).
    op.execute("UPDATE tenants SET plan = 'INDEPENDANT' WHERE is_paid = true")

    # 3. Nettoyage des anciennes colonnes, remplacées par 'plan' seul (fin des sources multiples).
    op.drop_column('tenants', 'employee_count')
    op.drop_column('tenants', 'annual_revenue_band')
    op.drop_column('tenants', 'company_size')
    op.drop_column('tenants', 'plan_id')
    op.drop_column('tenants', 'is_paid')
    op.execute("DROP TYPE IF EXISTS company_size")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('is_paid', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('tenants', sa.Column('plan_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('company_size', postgresql.ENUM('INDEPENDANT', 'PETITE_PME', 'MOYENNE_PME', 'ENTERPRISE', name='company_size'), autoincrement=False, nullable=False))
    op.add_column('tenants', sa.Column('annual_revenue_band', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('employee_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('tenants', 'plan')
    # ### end Alembic commands ###
