"""lot 43 fiche prospect

Revision ID: d43b8e1f5c27
Revises: c41a6f2d8e93
Create Date: 2026-10-02 14:02:18.786293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd43b8e1f5c27'
down_revision = 'c41a6f2d8e93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prospect_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('need', sa.String(length=300), nullable=True),
    sa.Column('condition', sa.String(length=16), nullable=True),
    sa.Column('budget', sa.String(length=100), nullable=True),
    sa.Column('payment', sa.String(length=16), nullable=True),
    sa.Column('timeline', sa.String(length=16), nullable=True),
    sa.Column('trade_in', sa.String(length=300), nullable=True),
    sa.Column('hot_alert_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'customer_id', name='uq_prospect_profile_customer')
    )
    op.create_index(op.f('ix_prospect_profiles_customer_id'), 'prospect_profiles', ['customer_id'], unique=False)
    op.create_index(op.f('ix_prospect_profiles_tenant_id'), 'prospect_profiles', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prospect_profiles_tenant_id'), table_name='prospect_profiles')
    op.drop_index(op.f('ix_prospect_profiles_customer_id'), table_name='prospect_profiles')
    op.drop_table('prospect_profiles')
    # ### end Alembic commands ###
