"""lot 13 regles de transmission

Revision ID: da2d67daf023
Revises: e02fbb66ccec
Create Date: 2026-09-26 14:27:34.717880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da2d67daf023'
down_revision = 'e02fbb66ccec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_handoff_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('refund_transfer', sa.Boolean(), nullable=False),
    sa.Column('complaint_policy', sa.String(length=16), nullable=False),
    sa.Column('discount_policy', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.add_column('message_signals', sa.Column('applied_rule', sa.String(length=40), nullable=True))
    op.add_column('message_signals', sa.Column('handoff_blocked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message_signals', 'handoff_blocked')
    op.drop_column('message_signals', 'applied_rule')
    op.drop_table('tenant_handoff_settings')
    # ### end Alembic commands ###
