"""phase 1 etiquettes des messages

Revision ID: e02fbb66ccec
Revises: 7eff3b216efc
Create Date: 2026-09-26 13:31:35.463623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e02fbb66ccec'
down_revision = '7eff3b216efc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_signals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('intents', sa.JSON(), nullable=False),
    sa.Column('objections', sa.JSON(), nullable=False),
    sa.Column('offered_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('taxonomy_version', sa.String(length=8), nullable=False),
    sa.Column('message_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index(op.f('ix_message_signals_conversation_id'), 'message_signals', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_message_signals_message_created_at'), 'message_signals', ['message_created_at'], unique=False)
    op.create_index(op.f('ix_message_signals_tenant_id'), 'message_signals', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_signals_tenant_id'), table_name='message_signals')
    op.drop_index(op.f('ix_message_signals_message_created_at'), table_name='message_signals')
    op.drop_index(op.f('ix_message_signals_conversation_id'), table_name='message_signals')
    op.drop_table('message_signals')
    # ### end Alembic commands ###
