"""sprint 22 - crm enrichissement client attribution qr

Revision ID: e0d26d938411
Revises: d1ee0898e653
Create Date: 2026-09-22 17:46:54.644337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0d26d938411'
down_revision = 'd1ee0898e653'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('acquisition_source', sa.String(length=64), nullable=True))
    op.add_column('customers', sa.Column('acquisition_detail', sa.String(length=255), nullable=True))
    op.add_column('customers', sa.Column('tags', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('customers', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('customers', sa.Column('marketing_consent', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('customers', sa.Column('detected_preferences', sa.JSON(), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'detected_preferences')
    op.drop_column('customers', 'marketing_consent')
    op.drop_column('customers', 'notes')
    op.drop_column('customers', 'tags')
    op.drop_column('customers', 'acquisition_detail')
    op.drop_column('customers', 'acquisition_source')
    # ### end Alembic commands ###
