"""lot 49 relances par email

Revision ID: e49c2a7d5b18
Revises: d43b8e1f5c27
Create Date: 2026-10-02 18:13:38.864897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e49c2a7d5b18'
down_revision = 'd43b8e1f5c27'
branch_labels = None
depends_on = None


# Lot 49 — les relances deviennent des emails : les textes par défaut d'avant (écrits pour WhatsApp,
# commençant par « Bonjour ») sont remplacés, seulement s'ils n'ont jamais été modifiés par le commerçant.
OLD_FIRST = "Bonjour, êtes-vous toujours intéressé(e) ? Je reste disponible pour répondre à vos questions."
OLD_SECOND = "Petit rappel : je suis toujours là si vous souhaitez reprendre notre échange."
NEW_FIRST = ("Nous n'avons pas eu de nouvelles depuis notre dernier échange. Avez-vous trouvé ce que vous "
             "cherchiez ? Nous restons à votre disposition sur WhatsApp pour répondre à vos questions.")
NEW_SECOND = ("Petit rappel : votre demande nous tient à cœur. Écrivez-nous sur WhatsApp, nous vous "
              "répondons tout de suite.")


def _swap(column: str, old: str, new: str) -> None:
    op.execute(sa.text(f"UPDATE tenant_followup_settings SET {column} = :new WHERE {column} = :old")
               .bindparams(new=new, old=old))


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_followup_settings', sa.Column('offer_text', sa.Text(), nullable=True))
    op.add_column('tenant_followup_settings', sa.Column('offer_code', sa.String(length=40), nullable=True))
    op.add_column('tenant_followup_settings', sa.Column('offer_ends_on', sa.Date(), nullable=True))
    # ### end Alembic commands ###
    _swap("first_message", OLD_FIRST, NEW_FIRST)
    _swap("second_message", OLD_SECOND, NEW_SECOND)


def downgrade() -> None:
    _swap("first_message", NEW_FIRST, OLD_FIRST)
    _swap("second_message", NEW_SECOND, OLD_SECOND)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_followup_settings', 'offer_ends_on')
    op.drop_column('tenant_followup_settings', 'offer_code')
    op.drop_column('tenant_followup_settings', 'offer_text')
    # ### end Alembic commands ###
