"""lot 2 - profil entreprise

Revision ID: e5cd1d50cf18
Revises: 55ab18294733
Create Date: 2026-09-23 12:04:57.370974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5cd1d50cf18'
down_revision = '55ab18294733'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('company_profile', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'company_profile')
    # ### end Alembic commands ###
