"""lot 29 creneaux de rendez-vous

Revision ID: f29b4c8e1d63
Revises: e28a6d3b7c52
Create Date: 2026-09-30 11:30:30.016729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f29b4c8e1d63'
down_revision = 'e28a6d3b7c52'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_appointment_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('online_booking', sa.Boolean(), nullable=False),
    sa.Column('opening_hours', sa.JSON(), nullable=False),
    sa.Column('slot_minutes', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', name='uq_appointment_settings_tenant')
    )
    op.create_index(op.f('ix_tenant_appointment_settings_tenant_id'), 'tenant_appointment_settings', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_appointment_settings_tenant_id'), table_name='tenant_appointment_settings')
    op.drop_table('tenant_appointment_settings')
    # ### end Alembic commands ###
