"""resilience ia politique de panne

Revision ID: fb4bae1d1734
Revises: da2d67daf023
Create Date: 2026-09-26 15:04:58.442310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb4bae1d1734'
down_revision = 'da2d67daf023'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_handoff_settings', sa.Column('ai_outage_policy', sa.String(length=16), server_default='RETRY_LATER', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_handoff_settings', 'ai_outage_policy')
    # ### end Alembic commands ###
